databases:
  - name: yummy_store
    databaseName: yummy_store
    user: yummy_store
services:
  - type: pserv
    name: pgbouncer
    runtime: docker
    plan: free
    repo: https://github.com/vikatiurne/api-yummy.git
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yummy_store
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50
